### ISSUE TITLE
Impossible shipwreck vault in expert mode

### ISSUE THREAD

**Issue by ChiCubed** [NewSoupVi/The-Witness-Randomizer-for-Archipelago#18]
In an Archipelago game I saw the following puzzle, which according to a brute force is impossible. (The symmetry is RotateLeft.)

![impossible_vault](https://user-images.githubusercontent.com/10266947/216887884-a123bec1-acc9-46e6-88d5-2764550d759d.png)

Randomiser was sigma expert, seed 417621 according to the tutorial door. I was using the [v3.1.0p3](https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/v3.1.0p3) executable. I guess this issue exists upstream as well, but I haven't tested so it's here for now.

I took a look at the generation code (the relevant function is [`Special::generateSoundDotReflectionSpecial`](https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/blob/76db2f99568a0fdba71a9d32cafb565137d98dd9/Source/Special.cpp#L338)) and I don't understand how it would be generating anything impossible. I don't have C++ dev tools set up so I haven't seen what all the variables look like when the generator gets to this puzzle, which would probably help. Maybe someone else can reproduce and debug (or maybe I'll get around to it eventually).

**Comment by NewSoupVi** [comment]
![image](https://user-images.githubusercontent.com/57900059/226501106-bce3deb7-cc32-4a82-baff-110af3786726.png)
![image](https://user-images.githubusercontent.com/57900059/226500137-b5318510-e71f-42c2-b391-1937ffd30fe2.png)

**Comment by NewSoupVi** [comment]
If you have any more questions as to why this solutions works, feel free to keep commenting on this issue, of course :)

I know there is a lot of unintuitive stuff in here (e.g. being able to collect the orange dots with the active line, which works in vanilla but never matters in vanilla. I've forwarded a note to Sigma to inlcude that detail in the FAQ / Wiki / Hints section.)
