### ISSUE TITLE
Bug?: Sigma Normal Mountain Final Room Left Pillar 2 seems to require Colored Squares when it shouldn't?

### ISSUE THREAD

**Issue by MisterSaward** [NewSoupVi/The-Witness-Randomizer-for-Archipelago#22]
In a recent multiworld I played, I was able to get to the mountain final room without Colored Squares, and was confused to see that the second left pillar was not able to be solved without them. Upon receiving them I was able to solve the puzzle, but it still only appeared to have the expected Black/White squares. I note that the logic in Archipelago only expects Black/White Squares for this puzzle. Am I just derping on something here or is this unintended?

I was playing on Sigma Normal, on version 3.2.0 of the randomiser.

**Comment by NewSoupVi** [comment]
Will be fixed next version :)
