### ISSUE TITLE
Town church lattice is enabled when disable non-randomized panels is disables

### ISSUE THREAD

**Issue by R3Ked** [NewSoupVi/The-Witness-Randomizer-for-Archipelago#29]
![image](https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/assets/20342336/8927d443-6b27-4e70-8a47-80129b5bbe34)
This panel isn't randomized at all, so I don't know why it's enabled here.

**Comment by Exempt-Medic** [comment]
Disable_non_randomized does not affect every non-randomized panel. There are exceptions like Town Church Lattice, Windmill Entry, Treehouse First Door, Town Maze, Mountaintop River Shape, and every single control panel. There's also the odd cases of Jungle Vault and Expert Orchard. This is, at least right now, working as intended

**Comment by NewSoupVi** [comment]
The `disable_non_randomized` mode is based on the behavior of the upstream Sigma rando, which itself is somewhat inconsistent.

This probably warrants changing, but I don't currently feel too motivated to work on this mode, as a new version of Sigma Rando with Desert, Bunker and Jungle randomisation is currently being developed. At that point I would probably just *drop* this mode entirely.
